services:
  # Backend Service
  - type: web
    name: numbers-home-api
    env: node
    region: ohio
    buildCommand: |
      cd backend
      npm install
      ls -la src/services/
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        sync: false
      - key: API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: numberhome-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://numberhome-backend.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false