services:
  # Backend Service
  - type: web
    name: numbers-home-api
    env: node
    region: ohio
    plan: starter
    buildCommand: |
      cd backend && npm ci
      cd ../frontend && npm ci
      npm run build
    startCommand: cd backend && NODE_ENV=production npm start
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      # Firebase Client Environment Variables
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_MEASUREMENT_ID
        sync: false