services:
  - type: web
    name: numbers-home-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://sebagutierrezf.github.io
      - key: API_KEY
        fromSecret: true
    runtime: "node/20"