services:
  - type: web
    name: numbers-home-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://sebagutierrezf.github.io
    runtime: "node/20"