services:
  - type: web
    name: numbers-home-api
    env: node
    region: ohio
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        sync: false
      - key: API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false